### ISSUE TITLE
Does this support external C files?

### ISSUE THREAD

**Issue by pksunkara** [karalabe/xgo#29] opened 2015-10-31 11:37 UTC
If you look at my sample cgo repo, https://github.com/pksunkara/cbind, I have some C++ files in `parser` folder.

I know xgo doesn't support external libraries but Does xgo support such kind of stuff?

**Comment by karalabe** [comment] 2015-11-02 08:21
;)

```
$ xgo github.com/pksunkara/cbind

$ ls -al
-rwxr-xr-x  1 root     root     6340312 Nov  2 10:19 cbind-android-21-arm
-rwxr-xr-x  1 root     root     1718668 Nov  2 10:19 cbind-darwin-386
-rwxr-xr-x  1 root     root     2157324 Nov  2 10:19 cbind-darwin-amd64
-rwxr-xr-x  1 root     root     2635653 Nov  2 10:19 cbind-linux-386
-rwxr-xr-x  1 root     root     3256820 Nov  2 10:19 cbind-linux-amd64
-rwxr-xr-x  1 root     root     2687883 Nov  2 10:19 cbind-linux-arm
-rwxr-xr-x  1 root     root     2191808 Nov  2 10:19 cbind-windows-386.exe
-rwxr-xr-x  1 root     root     2695698 Nov  2 10:19 cbind-windows-amd64.exe
```

Btw, it does support configure/make based, cross-compilation prepared C libraries too, though it's probably the rare gem when it works for all platforms (e.g. Gnu Multi-precision Library is one such which works out of the box).

**Comment by pksunkara** [comment] 2015-11-02 08:23
@karalabe What happens when those C++ files have OS specific triggers and code? Does this still work?

**Comment by karalabe** [comment] 2015-11-02 08:26
The best I can say is try it and report back :) If it's not too recent API addition, it should work. However, the OSX SDK included is not the freshest and the windows APIs are ported via `mingw` so there's probably a small lag between fresh APIs and having them implemented. I was playing around with assembling a fresh cross compiler image with fresher stuff in it, but I'm seeing some quirks so I cannot promise an ETA.

**Comment by pksunkara** [comment] 2015-11-02 08:33
Basically, I am trying to cross-compile a static binary from the following code, https://github.com/apiaryio/drafter. It's a gyp based build for cross compilation. I have been trying for days to compile it atleast on one platform but kept running into errors. I finally succeeded in building a sample repo yesterday and looks like you were able to cross-compile the same repo. :)

One more question, If I create a `parser/Makefile` for the C++ files, and link the generated `libbind.a` to the `go` files, will xgo still work?

**Comment by karalabe** [comment] 2015-11-02 08:37
We're using the GMP library that way, so theoretically it's workable. Practically, I can only say that you should try and maybe report back any issues. It's a very experimental thing (cross compiling C stuff is generally a very ugly thing).

**Comment by pksunkara** [comment] 2015-11-02 09:25
@karalabe I am sorry but I wasn't able to completely cross compile the repo as you did.

```
pksunkara@codecave [Desktop] #33  →  xgo github.com/pksunkara/cbind
Checking docker installation...
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/pksunkara/cbind...
Fetching main repository github.com/pksunkara/cbind...
github.com/pksunkara/cbind (download)
github.com/jessevdk/go-flags (download)
Assembling toolchain for android-21/arm...
Bootstrapping android-21/arm...
Compiling for android-21/arm...
Compiling for linux/amd64...
Compiling for linux/386...
Compiling for linux/arm...
Compiling for windows/amd64...
Compiling for windows/386...
Compiling for darwin/amd64...
go build github.com/pksunkara/cbind/parser: /usr/local/go/pkg/tool/linux_amd64/cgo: exit status 2
2015/11/02 14:53:13 Failed to cross compile package: exit status 1.
pksunkara@codecave [Desktop] #34  →  ls -al
total 19368
drwxr-xr-x  2 pksunkara pksunkara    4096 Nov  2 14:53 .
drwxr-xr-x 16 pksunkara pksunkara    4096 Nov  2 14:45 ..
-rwxr-xr-x  1 root      root      6340312 Nov  2 14:52 cbind-android-21-arm
-rwxr-xr-x  1 root      root      2635653 Nov  2 14:52 cbind-linux-386
-rwxr-xr-x  1 root      root      3256820 Nov  2 14:52 cbind-linux-amd64
-rwxr-xr-x  1 root      root      2687883 Nov  2 14:53 cbind-linux-arm
-rwxr-xr-x  1 root      root      2191808 Nov  2 14:53 cbind-windows-386.exe
-rwxr-xr-x  1 root      root      2695698 Nov  2 14:53 cbind-windows-amd64.exe
pksunkara@codecave [Desktop] #35  →  
```

**Comment by karalabe** [comment] 2015-11-02 09:29
Please see https://github.com/karalabe/xgo/issues/15#issuecomment-150090678. Docker hub is building the containers (OSX build tools) using a newer CPU instruction set than what you have available. Hence the pre-built image won't work on an older CPU architecture. You can work around this by building the docker image yourself (as detailed in the lined comment).

**Comment by pksunkara** [comment] 2015-11-02 09:38
Ah, Thanks for the help. I will try it later. I did encounter another problem when trying to build a static binary. Android is failing while the others are building. I don't really care about android but I wanted to tell you.

```
pksunkara@codecave [Desktop] #46  →  xgo -ldflags='-extldflags "-static"' -targets='android/*' github.com/pksunkara/cbind
Checking docker installation...
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/pksunkara/cbind...
Fetching main repository github.com/pksunkara/cbind...
github.com/pksunkara/cbind (download)
github.com/jessevdk/go-flags (download)
/build.sh: line 124: [: android: integer expression expected
Assembling toolchain for android-android/arm...
Bootstrapping android-android/arm...
Compiling for android-android/arm...
# github.com/pksunkara/cbind
/usr/local/go/pkg/tool/linux_amd64/link: running arm-linux-androideabi-g++ failed: exit status 1
/usr/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llog
/tmp/go-link-475151912/000001.o:gcc_util.c:function fatalf: error: undefined reference to '__android_log_vprint'
collect2: error: ld returned 1 exit status

2015/11/02 15:06:41 Failed to cross compile package: exit status 2.
```

**Comment by karalabe** [comment] 2015-11-02 09:41
Ah, the error message is really bad :)) You need to supply the platform along with the andorid target: e.g. `android-16/*`. I haven't put much effort into making this fool proof as I'm not sure I like the platform number in there.

**Comment by pksunkara** [comment] 2015-11-02 09:53
Well, I actually encountered it when building for all targets. A better error message is as follows:

```
pksunkara@codecave [Desktop] #36  →  xgo -ldflags='-extldflags "-static"' github.com/pksunkara/cbind
Checking docker installation...
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/pksunkara/cbind...
Fetching main repository github.com/pksunkara/cbind...
github.com/pksunkara/cbind (download)
github.com/jessevdk/go-flags (download)
Assembling toolchain for android-21/arm...
Bootstrapping android-21/arm...
Compiling for android-21/arm...
# github.com/pksunkara/cbind
/usr/local/go/pkg/tool/linux_amd64/link: running arm-linux-androideabi-g++ failed: exit status 1
/usr/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llog
/tmp/go-link-369601130/000001.o:gcc_util.c:function fatalf: error: undefined reference to '__android_log_vprint'
collect2: error: ld returned 1 exit status

2015/11/02 14:57:41 Failed to cross compile package: exit status 2.
```

The following error message uses `-x`

```
pksunkara@codecave [Desktop] #48  →  xgo -ldflags='-extldflags "-static"' -x github.com/pksunkara/cbind
Checking docker installation...
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/pksunkara/cbind...
Fetching main repository github.com/pksunkara/cbind...
github.com/pksunkara/cbind (download)
github.com/jessevdk/go-flags (download)
Assembling toolchain for android-21/arm...
Bootstrapping android-21/arm...
Compiling for android-21/arm...
WORK=/tmp/go-build910209547
mkdir -p $WORK/github.com/jessevdk/go-flags/_obj/
mkdir -p $WORK/github.com/jessevdk/
mkdir -p $WORK/github.com/pksunkara/cbind/parser/_obj/
cd /go/src/github.com/jessevdk/go-flags
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/jessevdk/go-flags.a -trimpath $WORK -p github.com/jessevdk/go-flags -complete -buildid 8f89ca9864d0a8b9369698dbcd4a1cc6415934ee -D _/go/src/github.com/jessevdk/go-flags -I $WORK -pack ./arg.go ./closest.go ./command.go ./completion.go ./convert.go ./error.go ./flags.go ./group.go ./help.go ./ini.go ./man.go ./multitag.go ./option.go ./optstyle_other.go ./parser.go ./termsize.go ./termsize_linux.go
mkdir -p $WORK/github.com/pksunkara/cbind/
cd /go/src/github.com/pksunkara/cbind/parser
CGO_LDFLAGS="-fPIE" /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/pksunkara/cbind/parser/_obj/ -importpath github.com/pksunkara/cbind/parser -- -I. -I $WORK/github.com/pksunkara/cbind/parser/_obj/ -fPIE parser.go
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -print-libgcc-file-name
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I. -I $WORK/github.com/pksunkara/cbind/parser/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_main.o -c $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_main.c
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I. -I $WORK/github.com/pksunkara/cbind/parser/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_export.o -c $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_export.c
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I. -I $WORK/github.com/pksunkara/cbind/parser/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/parser/_obj/parser.cgo2.o -c $WORK/github.com/pksunkara/cbind/parser/_obj/parser.cgo2.c
arm-linux-androideabi-g++ -I . -fPIC -marm -pthread -fmessage-length=0 -I. -I $WORK/github.com/pksunkara/cbind/parser/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/parser/_obj/Bind.cc.o -c ./Bind.cc
arm-linux-androideabi-g++ -I . -fPIC -marm -pthread -fmessage-length=0 -I. -I $WORK/github.com/pksunkara/cbind/parser/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/parser/_obj/cbind.cc.o -c ./cbind.cc
arm-linux-androideabi-g++ -I . -fPIC -marm -pthread -fmessage-length=0 -o $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_.o $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_main.o $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_export.o $WORK/github.com/pksunkara/cbind/parser/_obj/parser.cgo2.o $WORK/github.com/pksunkara/cbind/parser/_obj/Bind.cc.o $WORK/github.com/pksunkara/cbind/parser/_obj/cbind.cc.o -fPIE -pie
/usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/pksunkara/cbind/parser/_obj/ -dynpackage parser -dynimport $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_.o -dynout $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_import.go
arm-linux-androideabi-g++ -I . -fPIC -marm -pthread -fmessage-length=0 -o $WORK/github.com/pksunkara/cbind/parser/_obj/_all.o $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_export.o $WORK/github.com/pksunkara/cbind/parser/_obj/parser.cgo2.o $WORK/github.com/pksunkara/cbind/parser/_obj/Bind.cc.o $WORK/github.com/pksunkara/cbind/parser/_obj/cbind.cc.o -fPIE -Wl,-r -nostdlib /usr/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/libgcc.a -Wl,--build-id=none
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/pksunkara/cbind/parser.a -trimpath $WORK -p github.com/pksunkara/cbind/parser -buildid 35f75ff9dbf910e9a45b3d6df01220a607fc6cb3 -D _/go/src/github.com/pksunkara/cbind/parser -I $WORK -pack $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_gotypes.go $WORK/github.com/pksunkara/cbind/parser/_obj/parser.cgo1.go $WORK/github.com/pksunkara/cbind/parser/_obj/_cgo_import.go
pack r $WORK/github.com/pksunkara/cbind/parser.a $WORK/github.com/pksunkara/cbind/parser/_obj/_all.o # internal
mkdir -p $WORK/github.com/pksunkara/cbind/_obj/
mkdir -p $WORK/github.com/pksunkara/cbind/_obj/exe/
cd /go/src/github.com/pksunkara/cbind
CGO_LDFLAGS="-fPIE" /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/pksunkara/cbind/_obj/ -importpath github.com/pksunkara/cbind -- -I $WORK/github.com/pksunkara/cbind/_obj/ -fPIE main.go
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/pksunkara/cbind/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/_obj/_cgo_main.o -c $WORK/github.com/pksunkara/cbind/_obj/_cgo_main.c
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/pksunkara/cbind/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/_obj/_cgo_export.o -c $WORK/github.com/pksunkara/cbind/_obj/_cgo_export.c
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -I $WORK/github.com/pksunkara/cbind/_obj/ -fPIE -o $WORK/github.com/pksunkara/cbind/_obj/main.cgo2.o -c $WORK/github.com/pksunkara/cbind/_obj/main.cgo2.c
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -o $WORK/github.com/pksunkara/cbind/_obj/_cgo_.o $WORK/github.com/pksunkara/cbind/_obj/_cgo_main.o $WORK/github.com/pksunkara/cbind/_obj/_cgo_export.o $WORK/github.com/pksunkara/cbind/_obj/main.cgo2.o -fPIE -pie
/usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/pksunkara/cbind/_obj/ -dynpackage main -dynimport $WORK/github.com/pksunkara/cbind/_obj/_cgo_.o -dynout $WORK/github.com/pksunkara/cbind/_obj/_cgo_import.go
arm-linux-androideabi-gcc -I . -fPIC -marm -pthread -fmessage-length=0 -o $WORK/github.com/pksunkara/cbind/_obj/_all.o $WORK/github.com/pksunkara/cbind/_obj/_cgo_export.o $WORK/github.com/pksunkara/cbind/_obj/main.cgo2.o -fPIE -Wl,-r -nostdlib /usr/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/libgcc.a -Wl,--build-id=none
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/pksunkara/cbind.a -trimpath $WORK -p main -buildid a0bdea92e2abe57b92af57a19c3b50f63f67f6c6 -D _/go/src/github.com/pksunkara/cbind -I $WORK -I /go/pkg/android_arm -pack $WORK/github.com/pksunkara/cbind/_obj/_cgo_gotypes.go $WORK/github.com/pksunkara/cbind/_obj/main.cgo1.go $WORK/github.com/pksunkara/cbind/_obj/_cgo_import.go
pack r $WORK/github.com/pksunkara/cbind.a $WORK/github.com/pksunkara/cbind/_obj/_all.o # internal
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/github.com/pksunkara/cbind/_obj/exe/a.out -L $WORK -L /go/pkg/android_arm -extld=arm-linux-androideabi-g++ -buildmode=exe -buildid=a0bdea92e2abe57b92af57a19c3b50f63f67f6c6 -extldflags=-pie -extldflags=-Wl,--allow-multiple-definition -extldflags -static $WORK/github.com/pksunkara/cbind.a
# github.com/pksunkara/cbind
/usr/local/go/pkg/tool/linux_amd64/link: running arm-linux-androideabi-g++ failed: exit status 1
/usr/arm-linux-androideabi-4.9/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llog
/tmp/go-link-387999454/000001.o:gcc_util.c:function fatalf: error: undefined reference to '__android_log_vprint'
collect2: error: ld returned 1 exit status

2015/11/02 15:16:28 Failed to cross compile package: exit status 2.
```

**Comment by karalabe** [comment] 2015-11-03 17:09
This error message is caused by your manually specified ld flag. You request static compilation and it conflicts with some Android toolchain. It works fine without the extra ld flags.

**Comment by pksunkara** [comment] 2015-11-03 17:10
Yeah, I am okay with not building static binary for android. But I was just letting you know.

**Comment by karalabe** [comment] 2015-11-03 17:14
My guess is that the Android toolchain has a few libraries which it pulls off the device. And if you request static, then it fails linking as they are unavailable locally.

**Comment by karalabe** [comment] 2015-11-27 09:28
Closing as having been resolved.

**Closed by karalabe** 2015-11-27 09:28 UTC
